import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as THREE from 'three'

const Home: NextPage = () => {
  const scene = new THREE.Scene()
  console.log(scene)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>three.js</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
